wandb_version: 1

batch_size:
  value: 16
discount:
  value: 0.12443392358894814
epochs:
  value: 20
epsilon:
  value: 0.1360806408292181
epsilon_state_exploration:
  value: 0.8
learning_rate:
  value: 0.05630856489411432
num_episodes:
  value: 5
num_sample:
  value: 50
planning_steps:
  value: 10
target_update_frequency:
  value: 2
tau:
  value: 0.00013002675987952014
time_steps:
  value: 10
w1:
  value: 0.5
w2:
  value: 0.5
