
stages:
  - test
before_script:
  - echo "Starting CI/CD Pipeline"
  #- apt-get update
  #- apt-get install -y python3 python3-pip
  #- pip3 install torch


test:
  stage: test
  image: ubuntu:20.04
  script:
    - echo "Starting CI/CD Pipeline"
    - echo "Running tests"
    #- apt-get update
    #- apt-get install -y python3 python3-pip
    - pip3 install pytest
    - pytest tests
  only:
    - debug_branch
    - develop_branch
