
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - apt-get update && apt-get install -y python3 python3-pip python3-venv
  - python3 -m venv venv
  - source venv/bin/activate
  - pip3 install --cache-dir .cache/pip torch numpy pytest

sync_files:
  stage: prepare
  image: ubuntu:20.04
  script:
    - cp -r supporting_files/* tests/
  only:
    - debug_branch
    - develop_branch

test:
  stage: test
  image: ubuntu:20.04
  script:
    - source venv/bin/activate
    - pytest tests
  only:
    - debug_branch
    - develop_branch

