
stages:
  - test
before_script:
  - echo "Starting CI/CD Pipeline" 

test:
  stage: test
  image: ubuntu:20.04
  script:
    - set -e  # Stop on first error
    - echo "Starting CI/CD Pipeline"
    - echo "Running tests"
    - apt-get update -y
    - apt-get install -y python3 python3-pip python3-venv
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install pytest
    - pytest tests
  only:
    - debug_branch
    - develop_branch
  cache:
    paths:
      - venv/
