# Define the stages used in the pipeline. In this example, there's only one stage named 'test'.
stages:
  - test
# 'before_script' is a list of commands that run before each job's script.
before_script:
  - echo "Starting CI/CD Pipeline"  # This command prints a message to the log.

test:
  stage: test
  image: ubuntu:20.04
  script:
    - echo "Starting CI/CD Pipeline"
    - echo "Running tests"
    - apt-get update
    - apt-get install -y python3 python3-pip
    - pip3 install pytest
    - pytest tests
  only:
    - debug_branch
    - develop_branch
