stages:
  - prepare
  - test

variables:
  GIT_STRATEGY: fetch

before_script:
  - apt-get update
  - apt-get install -y python3 python3-pip
  - pip3 install --cache-dir .cache/pip torch numpy pytest

sync_files:
  stage: prepare
  image: ubuntu:20.04
  script:
    - echo "Syncing files from Supporting_files to tests..."
    - cp -r Supporting_files/* tests/
    - echo "Listing files in tests/ for verification:"
    - ls -lah tests/
  artifacts:
    paths:
      - tests/
  rules:
    - if: '$CI_COMMIT_BRANCH == "debug_branch"'

test:
  stage: test
  image: python:3.8 # ask the team what version of python they are using
  before_script:
    - apt-get update -qq  # -qq for less output
    - apt-get install -y make  # Install make
    - pip3 install --cache-dir .cache/pip -r requirements.txt  # Use the requirements file for dependencies
  script:
    - echo "Running tests..."
    - make test
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'

