wandb_version: 1

batch_size:
  value: 32
discount:
  value: 0.18044933096910337
epochs:
  value: 10
epsilon:
  value: 0.14997584276871326
epsilon_state_exploration:
  value: 0.8
learning_rate:
  value: 0.05255930414210816
num_episodes:
  value: 5
num_sample:
  value: 50
planning_steps:
  value: 10
target_update_frequency:
  value: 2
tau:
  value: 0.000185279001076084
w1:
  value: 0.5
w2:
  value: 0.5
