---
num_episodes: 5

threshold: 10

num_epochs: 100

time_steps: 30

batch_size: 30

buffer_size: 10000

num_sim: 10

tau: 0.5

num_train_AC: 10

critic_lr: 0.01

actor_lr: 0.0001

discount: 0.8

planning_steps: 10

planning_std: 0.1

actor_network:
  - 64
  - 64
  - 64

critic:
  - 64
  - 64
  - 64

reward_model:
  - 32
  - 64
  - 64
  - 32

next_state_model:
  - 32
  - 64
  - 64
  - 32