---
adjacent_list:
  0:
    - 1
  1:
    - 2
    - 3
    - 4
  2:
    - 5
  3:
    - 6
    - 7
  4:
    - 8
  5:
    - 9
  6:
    - 9
  7:
    - 9
  8:
    - 9
  9:
    - 10

miu_list:
  1: 0.00001
  2: 0.001
  3: 0.000001
  4: 0.000001
  5: 0.00001
  6: 0.01
  7: 0.001
  8: 0.01
  9: 0.01

transition_proba_all:
  0:
    1: 1
  1:
    2: 0.3
    3: 0.3
    4: 0.4
  2:
    5: 1
  3:
    6: 0.5
    7: 0.5
  4:
    8: 1
  5:
    9: 1
  6:
    9: 1
  7:
    9: 1
  8:
    9: 1
  9:
    10: 1

active_cap: 5
deactive_cap: 0.12

num_queues: 5

buffer_size_for_each_queue:
  1: 20
  2: 20
  3: 20
  4: 20
  5: 20
  6: 20
  7: 20
  8: 20
  9: 20
  10: 20
  11: 20
  12: 20

num_sim: 1

arrival_rate: 375