---
adjacent_list:
  0:
    - 1
    - 2
    - 3
  1:
    - 4
  2:
    - 5
  3:
    - 6
  4:
    - 7
  5:
    - 8
  6:
    - 9
  7:
    - 10
  8:
    - 10
  9:
    - 10

lambda_list:
  - 0.2
  - 0.2 
  - 0.2
  - 0.2
  - 0.2 
  - 0.2
  - 0.2
  - 0.2 
  - 0.2
  - 0.2

buffer_size:
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10

miu_list:
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1

active_cap: 5
deactive_cap: 0.12
