---
adjacent_list:
  0:
    - 1
  1:
    - 2
    - 3
    - 4
  2:
    - 5
  3:
    - 6
    - 7
  4:
    - 8
  5:
    - 9
  6:
    - 9
  7:
    - 9
  8:
    - 9
  9:
    - 10

miu_list:
  1: 0.5
  2: 1
  3: 1.2
  4: 0.2
  5: 0.2
  6: 0.2
  7: 0.2
  8: 0.2
  9: 0.2

transition_proba_all:
  0:
    1: 1
  1:
    2: 0.33
    3: 0.33
    4: 0.34
  2:
    5: 1
  3:
    6: 0.5
    7: 0.5
  4:
    8: 1
  5:
    9: 1
  6:
    9: 1
  7:
    9: 1
  8:
    9: 1
  9:
    10: 1

active_cap: 5
deactive_cap: 0.12

sef_rate_first_node: 0.095

num_queues: 5

buffer_size_for_each_queue:
  1: 20
  2: 20
  3: 20
  4: 20
  5: 20
  6: 20
  7: 20
  8: 20
  9: 20
  10: 20
  11: 20
  12: 20

num_sim: 5000

arrival_rate: 375