wandb_version: 1

batch_size:
  value: 64
discount:
  value: 0.19423382156910415
epochs:
  value: 20
epsilon:
  value: 0.16371251914473167
epsilon_state_exploration:
  value: 0.8
learning_rate:
  value: 0.0922700993482412
num_episodes:
  value: 5
num_sample:
  value: 50
planning_steps:
  value: 10
target_update_frequency:
  value: 2
tau:
  value: 0.0001799509752129255
time_steps:
  value: 10
w1:
  value: 0.5
w2:
  value: 0.5
